### ISSUE TITLE
Add db field for game end type

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live-client#94]

**Comment by Zamiell** [comment]
actually, it can probably be a more general end reason field
so that time out is different from 3 strikes

**Comment by aliblong** [comment]
could just be an enum
0 -> three strikes
1 -> timeout
2 -> abandoned

**Comment by Zamiell** [comment]
i was thinking
0 - completed game normally
1 - 3 strikes
2 - timeout
3 - abandoned

**Comment by Zamiell** [comment]
final mapping is:

0 - in progress
1 - normal
2 - strikeout
3 - timeout
4 - abandoned
